-- Fixes two critical issues found in a security audit of the `rooms` table:
--
-- 1. The existing policies (SELECT/INSERT/UPDATE all `USING/CHECK (true)`)
--    let anyone with the public anon key read or overwrite every room in
--    the database in one unfiltered request — no guessing required. This
--    migration scopes SELECT/UPDATE on ordinary room rows to a client that
--    presents the matching room code as a request header.
--
-- 2. Moderation-pending submissions are stored as ordinary rows in the same
--    table under `code = 'MOD-' || <room code>`. Nothing previously stopped
--    any client (i.e. any student) from reading that row directly. This
--    migration requires a separate `host_secret` (known only to the room's
--    creator and anyone they hand a phone-moderation-remote link to) to
--    read or write MOD- rows at all, and adds `append_pending_item()`, a
--    SECURITY DEFINER function students call to submit into the pending
--    queue without ever needing SELECT/UPDATE on the MOD- row themselves.
--
-- Run this in the Supabase SQL Editor. Review before running — it drops and
-- replaces every existing policy on `public.rooms`.

begin;

-- 1. New column: a per-room secret, generated by the app at room creation
-- and known only to the creating browser (and any phone-remote it's shared
-- with). Used to gate access to MOD- rows.
alter table public.rooms
  add column if not exists host_secret uuid not null default gen_random_uuid();

-- 2. Drop all existing policies on rooms (names may vary by project; this
-- avoids needing to know their exact current names).
do $$
declare
  pol record;
begin
  for pol in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'rooms'
  loop
    execute format('drop policy %I on public.rooms', pol.policyname);
  end loop;
end $$;

alter table public.rooms enable row level security;

-- 3. SELECT: ordinary room rows are readable by anyone who supplies the
-- matching room code as a header (this is what every legitimate class
-- member — student or teacher — already knows). MOD- rows are readable
-- only by a request that supplies the matching host_secret header.
create policy "rooms_select_scoped"
on public.rooms
for select
to public
using (
  (code not like 'MOD-%'
    and code = (current_setting('request.headers', true)::json ->> 'x-room-code'))
  or
  (host_secret::text = (current_setting('request.headers', true)::json ->> 'x-host-secret'))
);

-- 4. UPDATE: same scoping. Ordinary rows stay writable by any class member
-- who knows the room code (needed for join/roster/votes/likes/config
-- toggles from student devices) — this migration does not add per-column
-- restrictions within a room. MOD- rows require the host_secret; students
-- never update them directly (see append_pending_item below).
create policy "rooms_update_scoped"
on public.rooms
for update
to public
using (
  (code not like 'MOD-%'
    and code = (current_setting('request.headers', true)::json ->> 'x-room-code'))
  or
  (host_secret::text = (current_setting('request.headers', true)::json ->> 'x-host-secret'))
)
with check (
  (code not like 'MOD-%'
    and code = (current_setting('request.headers', true)::json ->> 'x-room-code'))
  or
  (host_secret::text = (current_setting('request.headers', true)::json ->> 'x-host-secret'))
);

-- 5. INSERT: unchanged — anonymous room creation stays open. A client can
-- only ever insert a brand-new row (their own), not overwrite someone
-- else's, since existing rows are protected by the UPDATE policy above.
create policy "rooms_insert_open"
on public.rooms
for insert
to public
with check (true);

-- 6. Before running: confirm posts/words/votes/responses are `jsonb`
-- (not `json`) columns — e.g. `select column_name, data_type from
-- information_schema.columns where table_name = 'rooms';`. The `||` append
-- below is jsonb-only; if any of these are `json`, cast the two operands to
-- `::jsonb` and the final expression back to `::json` in the CASE branches.
--
-- Server-side append for moderated submissions. Runs with elevated
-- privileges (bypasses RLS) so it can write into the MOD- row without ever
-- handing SELECT/UPDATE on that row to the caller — the submitting
-- student's browser gets back only success/failure, never the array
-- contents, so it can no longer see other students' pending submissions.
create or replace function public.append_pending_item(
  p_code text,
  p_column text,
  p_item jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  mod_code text := 'MOD-' || p_code;
  affected int;
begin
  if p_column not in ('posts', 'words', 'votes', 'responses') then
    raise exception 'append_pending_item: invalid column %', p_column;
  end if;

  update public.rooms
  set
    updated_at = now(),
    posts     = case when p_column = 'posts'     then coalesce(posts, '[]'::jsonb) || jsonb_build_array(p_item) else posts end,
    words     = case when p_column = 'words'     then coalesce(words, '[]'::jsonb) || jsonb_build_array(p_item) else words end,
    votes     = case when p_column = 'votes'     then coalesce(votes, '[]'::jsonb) || jsonb_build_array(p_item) else votes end,
    responses = case when p_column = 'responses' then coalesce(responses, '[]'::jsonb) || jsonb_build_array(p_item) else responses end
  where code = mod_code;

  get diagnostics affected = row_count;
  if affected = 0 then
    raise exception 'append_pending_item: room % not found or not initialized for moderation', p_code;
  end if;
end;
$$;

revoke all on function public.append_pending_item(text, text, jsonb) from public;
grant execute on function public.append_pending_item(text, text, jsonb) to anon, authenticated;

commit;

-- ---------------------------------------------------------------------------
-- Verify after running:
--
--   select relname, relrowsecurity, relforcerowsecurity
--   from pg_class where relnamespace = 'public'::regnamespace and relkind = 'r';
--
--   select policyname, cmd, qual, with_check
--   from pg_policies where schemaname = 'public' and tablename = 'rooms';
--
-- Known caveat to test after deploying the matching app change: Supabase
-- Realtime's `postgres_changes` evaluates these same RLS policies, but over
-- the replication connection, not a per-request HTTP call — so the
-- `request.headers` header this migration relies on may not be populated
-- there the way it is for ordinary REST calls. If live updates (teacher's
-- dashboard refreshing when a student submits) stop appearing without a
-- manual refresh after this change, that's why; the REST-based reads
-- (kvGet) are unaffected and will still return correct, properly-scoped
-- data on demand. Come back and we can add an interval-based poll as a
-- fallback if Realtime turns out not to deliver events under these policies.
-- ---------------------------------------------------------------------------
